---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: '2.3.0'

run:
  path: sh
  args:
  - -exec
  - |
    git clone git@github.com:vizjerai/testing-ci.git
    cd testing-ci
    bundle install --no-document
    bundle exec rspec spec
