---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: '2.3.0'

run:
  path: sh
  args:
  - -exec
  - |
    git clone https://github.com/vizjerai/testing-ci.git
    cd testing-ci
    bundle install
    bundle exec rspec spec
